# NOTE: Follow the instructions below to run this file
# Install "REST Client" extension in VS Code to run this file
# Link: https://marketplace.visualstudio.com/items?itemName=humao.rest-client 
# Or Search for "REST Client" in Extensions in VS Code or paste extension ID "humao.rest-client" in Extensions search


@host = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjY3Mjk5ZGU0MjM5MTNjODI3OWM3ZDQiLCJpYXQiOjE3MTgwMzY4OTQsImV4cCI6MTcyODQwNDg5NH0.dwcozVJdfBiVRohtFJmecP4piPd0QxvlhLvlbr6qAKI


# Authentication
POST {{host}}/api/user/login
content-type: application/json

{
    "email": "hamada@gmail.com",
    "password": "kdkdk78787878"
}
###

POST {{host}}/api/user/signup
content-type: application/json

{
    "email": "hamada@gmail.com",
    "password": "kdkdk78787878",
    "firstName": "Ali",
    "lastName": "Khalil"
}
###

POST {{host}}/api/user/resetPassword
content-type: application/json
Authorization: Bearer {{token}}

{
    "oldPassword": "kdkdk78787878",
    "newPassword": "dhdhdhhdhdd"
}
###

# User CRUD
GET {{host}}/api/user/me
content-type: application/json
Authorization: Bearer {{token}}

###

DELETE {{host}}/api/user
content-type: application/json
Authorization: Bearer {{token}}

###

PUT {{host}}/api/user
content-type: application/json
Authorization: Bearer {{token}}

{
    "firstName": "Peter",
    "lastName": "Khalil Fahmy"
}
###

# OTP
POST {{host}}/api/user/otp/verify
content-type: application/json
Authorization: Bearer {{token}}

{
    "otp": "123456"
}
###
POST {{host}}/api/user/otp/resend
content-type: application/json
Authorization: Bearer {{token}}
###

# Documents Operations
# NOTE: Upload file, Upload folder, and Handwritten can be tested only on Postman or similar tools
POST {{host}}/api/upload/process
content-type: application/json
Authorization: Bearer {{token}}

{
    "chatId": "6666ffd0cc6a3553e2f46b15"
}
###

POST {{host}}/api/query/query-process
content-type: application/json
Authorization: Bearer {{token}}

{
    "query": "WHat does this pdf contain?",
    "chatId": "6666ffd0cc6a3553e2f46b15",
    "modelType": "openai"
}
###

# Chat CRUD
GET {{host}}/api/chat
content-type: application/json
Authorization: Bearer {{token}}
###

GET {{host}}/api/chat/6666ffd0cc6a3553e2f46b15
content-type: application/json
Authorization: Bearer {{token}}
###

DELETE {{host}}/api/chat/6666ffd0cc6a3553e2f46b15
content-type: application/json
Authorization: Bearer {{token}}
###

PUT {{host}}/api/chat/6666ffd0cc6a3553e2f46b15
content-type: application/json
Authorization: Bearer {{token}}

{
    "chatName": "New Title"
}
###

POST https://api.openai.com/v1/chat/completions
content-type: application/json
Authorization: Bearer 

{
    "model": "gpt-3.5-turbo-16k",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Hello!"
      }
    ]
  }